### ISSUE TITLE
package.json file is not allowing cjs to work

### ISSUE THREAD

**Issue by northkode** [rjbultitude/darkskyjs#5]
the main attribute in your package.json file is not pointing to lib/darkskyjs so it fails es6 loading.

**Comment by rjbultitude** [comment]
Thanks for raising this @northkode. I have applied the fix and published. Latest version is 0.1.1.
Please let me know if your app is now working correctly and I'll close the issue

**Comment by northkode** [comment]
cool, thanks, Ill give it a go

**Comment by rjbultitude** [comment]
Hi @northkode 
I'm going to close this ticket. Please let me know if you're still experiencing a problem.
